feat: database create event endpoint
lou-weng/schedulii pull request #42
Opened 2023-01-07 10:06 UTC by erickexinlu

## Describe your changes

## JIRA Ticket ID

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] If it is a core feature, I have added thorough tests.

2023-01-07 10:10 UTC, lou-weng commented on Makefile
> +br_backend: build_backend run
wats this for

2023-01-07 10:12 UTC, erickexinlu commented on Makefile
> +br_backend: build_backend run
i just made so i wouldn't have to run make build_backend and then make run when i make some edit to the backend, so i don't have to build the frontend every time and can just use one command

2023-01-07 10:14 UTC, lou-weng commented on backend/src/services/data/event_data_service.go
> +			  WHERE EventID = ($1)`
<img width="453" alt="Screenshot 2023-01-07 at 2 13 58 AM" src="https://user-images.githubusercontent.com/56288712/211145278-cf890146-4ea9-41d0-b307-919c43357248.png">

2023-01-07 10:15 UTC, lou-weng requested changes

2023-01-07 10:15 UTC, lou-weng commented on backend/src/services/data/event_data_service.go
> +func CreateEvent(env *models.Env, event models.Event) {
return an error type

if no error, return nil

2023-01-07 10:16 UTC, erickexinlu commented on backend/src/services/data/event_data_service.go
> +			  WHERE EventID = ($1)`
![image](https://user-images.githubusercontent.com/112150559/211145349-db4072c6-4b8d-4de5-86ea-687491718886.png)
argh it's being weird again, looks normal on my vscode

2023-01-07 10:17 UTC, lou-weng requested changes

2023-01-07 10:17 UTC, lou-weng commented on backend/go.mod
> +	github.com/georgysavva/scany/v2 v2.0.0 // indirect
remove

2023-01-07 10:17 UTC, lou-weng commented on backend/src/main.go
> +	// remove this later
what is this comment for

2023-01-07 10:17 UTC, lou-weng commented on backend/src/services/data/event_data_service.go
> +	fmt.Println("\nRow updated successfully!")
return error type for function, nil if there is no error

2023-01-07 10:17 UTC, lou-weng commented on backend/src/services/data/event_data_service.go
> +func ReadEvent(env *models.Env, event models.Event) models.Event {
function should return type of (models.Events, error)

2023-01-07 10:17 UTC, erickexinlu commented on backend/src/services/data/event_data_service.go
> +			  WHERE EventID = ($1)`
to be safe i made the entire line out of spaces for the next commit

2023-01-07 10:18 UTC, erickexinlu commented on backend/src/main.go
> +	// remove this later
removed

2023-01-07 23:30 UTC, lou-weng commented on Makefile
> +br_backend: build_backend run
I would change the name of the command br_backend is confusing

2023-01-08 09:38 UTC, lou-weng approved these changes

2023-01-09 01:32 UTC, merged